import { gql, useQuery } from '@apollo/client';
import { Button, Typography } from '@mui/material';
import Head from 'next/head';
import { FiChevronsLeft } from 'react-icons/fi';

const GET_EPISODES = gql`
  query GetEpisodes {
    episodes {
      info {
        count
        pages
        next
        prev
      }
      results {
        id
        name
      }
    }
  }
`;

export default function Home() {
  const { loading, data, error } = useQuery(GET_EPISODES);
  console.log({ loading, data, error });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          height: '100vh',
        }}
      >
        <Typography variant="h1" fontSize={24}>
          Hey! :)
        </Typography>
        <Button variant="contained" startIcon={<FiChevronsLeft />}>
          Hello World!
        </Button>
      </main>
    </>
  );
}
